### ISSUE TITLE
Avalonia version is not available on Linux

### ISSUE THREAD

**Issue by jinyuttt** [ahopper/Mapsui#1]
Avalonia version is not available on Linux

**Comment by ahopper** [comment]
The current build uses the avalonia nightly feed see https://github.com/AvaloniaUI/Avalonia/wiki/Using-nightly-build-feed this uses an updated version of skiasharp which matches the mapsui version, if starting a project now it makes sense to use this version as the next stable release (0.1.0) is due out fairly soon and will use it.

**Comment by jinyuttt** [comment]
OK
